### ISSUE TITLE
Bye message of imap stops the bot

### ISSUE THREAD

**Issue by maikell** [nitmir/irc-email-notifier#2]
See:
  40:32.38 MainThread ["<class 'imaplib2.imaplib2.abort'>: command: LOGOUT => connection terminated"]
Is there a way to work around it? Addon:

Traceback (most recent call last):
  File "./notifier.py", line 290, in <module>
    Notifier(**params)
  File "./notifier.py", line 167, in __init__
    data = self.irc.recv ( 4096 )
socket.timeout: timed out

**Comment by DarkTexas** [comment]
any fix on that???
